# Generated by Django 5.2.4 on 2025-07-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('beneficiary_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('contact', models.CharField(max_length=50)),
                ('registration_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiaryDocuments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('beneficiary_id', models.IntegerField()),
                ('document_url', models.URLField()),
                ('doc_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiaryProjectMap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('beneficiary_id', models.IntegerField()),
                ('project_id', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectBeneficiaries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_id', models.IntegerField()),
                ('beneficiary_id', models.IntegerField()),
            ],
        ),
    ]
